stages:
  - build
  - deploy

variables:
  IMAGE_AIRFLOW: $CI_REGISTRY_IMAGE/airflow:$CI_COMMIT_SHORT_SHA
  IMAGE_AIRFLOW_LATEST: $CI_REGISTRY_IMAGE/airflow:latest
  IMAGE_API: $CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA
  IMAGE_API_LATEST: $CI_REGISTRY_IMAGE/api:latest
  IMAGE_SPARK: $CI_REGISTRY_IMAGE/spark:$CI_COMMIT_SHORT_SHA
  IMAGE_SPARK_LATEST: $CI_REGISTRY_IMAGE/spark:latest

build-airflow:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f infra/Dockerfile.airflow -t $IMAGE_AIRFLOW -t $IMAGE_AIRFLOW_LATEST .
    - docker push $IMAGE_AIRFLOW
    - docker push $IMAGE_AIRFLOW_LATEST
  only:
    - main
    - master

build-api:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f infra/Dockerfile.api -t $IMAGE_API -t $IMAGE_API_LATEST .
    - docker push $IMAGE_API
    - docker push $IMAGE_API_LATEST
  only:
    - main
    - master

build-spark:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f infra/Dockerfile.spark -t $IMAGE_SPARK -t $IMAGE_SPARK_LATEST .
    - docker push $IMAGE_SPARK
    - docker push $IMAGE_SPARK_LATEST
  only:
    - main
    - master

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:latest
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
  script:
    - kubectl create namespace efrei-big-data --dry-run=client -o yaml | kubectl apply -f -
    - kubectl delete secret regcred -n efrei-big-data --ignore-not-found
    - kubectl create secret docker-registry regcred -n efrei-big-data --docker-server=$CI_REGISTRY --docker-username=$K8S_REGISTRY_USER --docker-password=$K8S_REGISTRY_PASSWORD
    - kubectl delete secret efrei-secrets -n efrei-big-data --ignore-not-found
    - >
      kubectl create secret generic efrei-secrets -n efrei-big-data
      --from-literal=POSTGRES_PASSWORD="$POSTGRES_PASSWORD"
      --from-literal=AIRFLOW_ADMIN_PASSWORD="$AIRFLOW_ADMIN_PASSWORD"
      --from-literal=AIRFLOW_INVIT_PASSWORD="$AIRFLOW_INVIT_PASSWORD"
    - kubectl apply -f infra/k8s.yaml
    - kubectl rollout restart deployment/postgres -n efrei-big-data
    - kubectl rollout restart deployment/airflow -n efrei-big-data
    - kubectl rollout restart deployment/api -n efrei-big-data
    - kubectl rollout restart deployment/namenode -n efrei-big-data
    - kubectl rollout restart deployment/datanode -n efrei-big-data
    - kubectl rollout restart deployment/spark-master -n efrei-big-data
    - kubectl rollout restart deployment/spark-worker -n efrei-big-data
  only:
    - main
    - master
