FROM apache/airflow:3.0.0-python3.11

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless && \
    rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
RUN pip install --no-cache-dir psycopg2-binary pyspark==3.5.1 apache-airflow-providers-apache-spark

COPY --chown=airflow:root dags/ /opt/airflow/dags/
COPY --chown=airflow:root spark/ /opt/airflow/spark/
COPY --chown=airflow:root ingestion/ /opt/airflow/ingestion/
COPY --chown=airflow:root infra/airflow/entrypoint.sh /entrypoint.sh

USER root
RUN chmod +x /entrypoint.sh
USER airflow

ENTRYPOINT ["/entrypoint.sh"]
