FROM apache/airflow:3.0.0-python3.11

USER airflow

COPY --chown=airflow:root dags/ /opt/airflow/dags/
COPY --chown=airflow:root infra/airflow/entrypoint.sh /entrypoint.sh

USER root
RUN chmod +x /entrypoint.sh
USER airflow

ENTRYPOINT ["/entrypoint.sh"]
